### ISSUE TITLE
flip should only reverse the first two arguments

### ISSUE THREAD

**Issue by ericelliott** [casualjs/f#6]
```
flip :: (a -> b -> c) -> b -> a -> c
```

Wouldn't this implementation reverse the args instead of flip the first two?

``` js
function flip (f) {
  return (...args) => f(...args.reverse());
}

const foo = (a, b, c) => [a, b, c];

const test = flip(foo); // ['c', 'b', 'a'] -- should return ['b','a','c']
```

**Comment by mateogianolio** [comment]
The Haskell version is only defined for two arguments.
The JavaScript version is generalised to work with multiple arguments and therefore the flip operation is also scaled to work with multiple arguments.
